# Generated by Django 2.0.6 on 2018-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RECIPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHECK', models.IntegerField(default=0)),
                ('USER_KEY', models.CharField(default='`', max_length=50)),
                ('USER_NAME', models.CharField(default='`', max_length=50)),
                ('R_NAME', models.CharField(default='`', max_length=100)),
                ('F_NAME', models.CharField(default='`', max_length=100)),
                ('INGRED', models.CharField(default='`', max_length=1000)),
                ('ORDER_1', models.CharField(default='`', max_length=10000)),
                ('PICK', models.IntegerField(default=5)),
                ('DATE', models.CharField(default='`', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHECK', models.IntegerField(default=0)),
                ('KEY', models.CharField(default='`', max_length=50)),
                ('NAME', models.CharField(default='`', max_length=50)),
                ('COMMAND', models.CharField(default='`', max_length=500)),
                ('HISTORY', models.CharField(default='`', max_length=500)),
                ('LEVEL', models.IntegerField(default=5)),
            ],
        ),
    ]
