# Generated by Django 2.0.6 on 2018-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipick_Main', '0002_auto_20180714_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='COOK',
            field=models.IntegerField(default=0),
        ),
    ]
