# Generated by Django 2.0.6 on 2018-06-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_update_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='G_Level',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='goods',
            name='G_Rate',
            field=models.IntegerField(default=50),
        ),
    ]
