# Generated by Django 2.0.6 on 2018-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_KEY', models.CharField(max_length=50)),
                ('USER_NAME', models.CharField(max_length=20)),
                ('USER_COMMAND', models.CharField(default='-1', max_length=100)),
                ('USER_LEVEL', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='USER_SERVICE_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_KEY', models.CharField(max_length=50)),
                ('USER_NAME', models.CharField(max_length=20)),
                ('USER_CLASS_1', models.CharField(max_length=200)),
                ('USER_CLASS_2', models.CharField(max_length=200)),
                ('USER_CLASS_3', models.CharField(max_length=200)),
                ('USER_CLASS_4', models.CharField(max_length=200)),
                ('USER_CLASS_5', models.CharField(max_length=200)),
                ('USER_CLASS_6', models.CharField(max_length=200)),
                ('USER_CLASS_7', models.CharField(max_length=200)),
                ('USER_CLASS_8', models.CharField(max_length=200)),
                ('USER_CLASS_9', models.CharField(max_length=200)),
                ('USER_CLASS_10', models.CharField(max_length=200)),
                ('USER_CLASS_11', models.CharField(max_length=200)),
                ('USER_CLASS_12', models.CharField(max_length=200)),
                ('USER_CLASS_13', models.CharField(max_length=200)),
                ('USER_CLASS_14', models.CharField(max_length=200)),
                ('USER_CLASS_15', models.CharField(max_length=200)),
            ],
        ),
    ]
