# Generated by Django 2.0.6 on 2018-06-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univtalk_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_NUM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_1',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_10',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_11',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_12',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_13',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_14',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_15',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_2',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_3',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_4',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_5',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_6',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_7',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_8',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_9',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
