# Generated by Django 2.0.6 on 2018-06-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univtalk_main', '0002_auto_20180625_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_1',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_10',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_11',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_12',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_13',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_14',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_15',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_2',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_3',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_4',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_5',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_6',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_7',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_8',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_9',
        ),
        migrations.RemoveField(
            model_name='user_service_1',
            name='USER_CLASS_NUM',
        ),
    ]
