# Generated by Django 2.0.6 on 2018-06-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univtalk_main', '0003_auto_20180626_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_10_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_10_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_10_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_10_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_10_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_10_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_10_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_11_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_11_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_11_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_11_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_11_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_11_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_11_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_12_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_12_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_12_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_12_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_12_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_12_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_12_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_13_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_13_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_13_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_13_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_13_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_13_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_13_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_14_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_14_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_14_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_14_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_14_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_14_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_14_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_15_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_15_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_15_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_15_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_15_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_15_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_15_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_1_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_1_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_1_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_1_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_1_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_1_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_1_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_2_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_2_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_2_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_2_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_2_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_2_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_2_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_3_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_3_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_3_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_3_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_3_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_3_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_3_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_4_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_4_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_4_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_4_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_4_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_4_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_4_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_5_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_5_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_5_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_5_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_5_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_5_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_5_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_6_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_6_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_6_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_6_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_6_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_6_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_6_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_7_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_7_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_7_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_7_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_7_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_7_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_7_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_8_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_8_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_8_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_8_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_8_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_8_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_8_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_9_DAY',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_9_END',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_9_MASTER',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_9_NAME',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_9_ROOM',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_9_START',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_9_TEMP',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_NAME',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_service_1',
            name='USER_CLASS_NUM',
            field=models.IntegerField(default=0),
        ),
    ]
