# Generated by Django 2.0.6 on 2018-06-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univtalk_main', '0004_auto_20180626_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_10_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_11_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_12_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_13_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_14_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_15_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_2_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_3_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_4_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_5_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_6_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_7_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_8_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_9_DAY',
            field=models.CharField(default='-1', max_length=5),
        ),
    ]
