# Generated by Django 2.0.6 on 2018-06-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univtalk_main', '0005_auto_20180626_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_10_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_11_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_12_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_13_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_14_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_15_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_1_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_2_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_3_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_4_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_5_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_6_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_7_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_8_TEMP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_service_1',
            name='USER_CLASS_9_TEMP',
            field=models.IntegerField(default=0),
        ),
    ]
