# Generated by Django 2.0.6 on 2018-06-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univtalk_main', '0006_auto_20180626_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USER_UNIV',
            field=models.CharField(default='-1', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_KEY',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_NAME',
            field=models.CharField(default='-1', max_length=20),
        ),
    ]
