# Generated by Django 2.0.6 on 2018-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userkey', models.CharField(max_length=20)),
                ('G1', models.IntegerField(default=0)),
                ('G2', models.IntegerField(default=0)),
                ('G3', models.IntegerField(default=0)),
                ('G4', models.IntegerField(default=0)),
                ('G5', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userkey', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('money', models.IntegerField(default=1000000)),
            ],
        ),
    ]
