# Generated by Django 2.0.6 on 2018-06-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_main', '0002_user_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_Code', models.CharField(max_length=5)),
                ('G_Name', models.CharField(max_length=20)),
                ('G_Price', models.IntegerField(default=10000)),
                ('G_Amount', models.IntegerField(default=1000000)),
            ],
        ),
    ]
