# Generated by Django 2.0.6 on 2018-06-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_main', '0003_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='command',
            field=models.CharField(default='', max_length=100),
        ),
    ]
