# Generated by Django 2.0.6 on 2018-06-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_main', '0004_user_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='box',
            name='userkey',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='userkey',
            field=models.CharField(max_length=50),
        ),
    ]
