# Generated by Django 2.0.6 on 2018-06-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_main', '0005_auto_20180621_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ingame',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
