# Generated by Django 2.0.6 on 2018-06-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_main', '0007_auto_20180622_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bank',
            name='lucky_chance',
            field=models.IntegerField(default=0),
        ),
    ]
