# Generated by Django 2.0.6 on 2018-06-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot_main', '0009_auto_20180623_0112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Box',
            new_name='User_Box',
        ),
    ]
